Feat : 이메일 인증 구현 [Jira] PQ-48(하위 이슈 PQ-89,PQ-90,PQ-91,PQ-92,PQ-93), PQ-52
100-hours-a-week/5-chunsik-4Q-be pull request #4
Opened 2024-08-15 08:15 UTC by kimdaegeon0918

### 개요
- 이메일 인증, 재전송 구현

### 리뷰어가 꼭 봐줬으면 하는 부분
- ERD Email_Confirm 테이블과 API 명세서에 맞춰서 구현
- 인증번호는 AES 알고리즘으로 암호화 해서 DB 저장, 복호화해서 검증
- createAt과 현재시간 비교해서 3분 초과하면 인증번호 만료 처리
- 동일 이메일에 대한 데이터가 있으면 추가하지 않고 기존의 데이터를 업데이트 하는 방식으로 구현
- 재전송요청은 다른 엔드포인트 API를 구현하지 않고 쿠키를 사용해서 쿠키에 요청횟수를 저장해서 최대 요청 횟수가 넘으면 429 TOO MANY REQUESTS 반환하도록 구현

### Jira ISSUE Keys
- PQ-48(하위 이슈 PQ-89,PQ-90,PQ-91,PQ-92,PQ-93), PQ-52

2024-08-15 09:10 UTC, ZZ3n requested changes
코드 너무 깔끔하고 좋습니다!
다만, 우리(5팀)가 코드적으로 협의 된 부분이 적어서 리뷰 할 게 많네요

2024-08-15 09:10 UTC, ZZ3n commented on src/main/java/org/chunsik/pq/email/service/EmailService.java
> +        Optional<EmailConfirm> existingEmailConfirmOpt = emailConfirmRepository.findByEmail(email);
``` java
EmailConfirm emailConfirm = emailConfirmRepository.findByEmail(email)
                .orElseGet(() -> {
                    EmailConfirm newEmailConfirm = new EmailConfirm();
                    newEmailConfirm.setEmail(email);
                    newEmailConfirm.setSecretCode(encryptedCode);
                    newEmailConfirm.setCreatedAt(LocalDateTime.now());
                    newEmailConfirm.setIsSend(true);
                    newEmailConfirm.setSendedAt(LocalDateTime.now());
                    return newEmailConfirm;
                });
```
이런 식으로 Optional 이용하시면 좋을 것 같습니다~
```java
EmailConfirm emailConfirm = emailConfirmRepository.findByEmail(email)
        .orElseGet(() -> {
            EmailConfirm newEmailConfirm = EmailConfirm.readyToSendingNow(email, encryptedCode);
            return newEmailConfirm;
        });
```

그리고 Entity의 setter 사용을 지양하고, 생성자를 이용해 생성하고, 변경사항은 Public 메서드를 이용해서 변경하는 걸로 하겠습니다.
관련 내용은 노션에 추가적으로 작성해서 전달드릴게요!

2024-08-15 09:10 UTC, ZZ3n commented on src/main/resources/application.yml
> +    url: jdbc:mysql://localhost:3306/chunsik_db
악 이거는 개인별 설정으로 분리해야겠네요
금일이나 차일 내로 작업해서 올리겠습니다!

2024-08-15 09:10 UTC, ZZ3n commented on build.gradle
> +	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
jwt...는 왜... 추가됬나요? 🤔

2024-08-15 12:44 UTC, ZZ3n requested changes
`진짜진짜진짜로정말로마지막.review`
 Exception 부분만 부탁드립니다. 🙇‍♂️

2024-08-15 12:44 UTC, ZZ3n commented on src/main/java/org/chunsik/pq/email/model/EmailConfirm.java
이거 `@Column` 다 삭제해도.... 작동 잘 하던가요?

2024-08-15 12:44 UTC, ZZ3n commented on src/main/java/org/chunsik/pq/email/controller/EmailController.java
> +    @ExceptionHandler(RuntimeException.class)
이거... `RuntimeException`으로 처리하면 좀 문제가 될 수 도 있겠는데요?

`RuntimeException`이면 일반적인 자바 예외 처리 클래스라,
`EmailController` 코드 내에서 발생하는 모든 런타임 예외가 이 방식으로 response가 나갈 겁니다.

따로 exception 클래스를 만들어서 처리하는 게 좋을 것 같습니다.

![image](https://github.com/user-attachments/assets/ec829b62-07c4-4ec3-93b2-c90f4af75a11)

2024-08-15 12:44 UTC, ZZ3n commented on src/main/java/org/chunsik/pq/email/service/EmailService.java
> +        Optional<Cookie> requestCountCookieOpt = getCookie(request, REQUEST_COUNT_COOKE_NAME);
오타났습니다 😅
`REQUEST_COUNT_COOKE_NAME` -> `REQUEST_COUNT_COOKIE_NAME`

2024-08-15 12:44 UTC, ZZ3n commented on src/main/java/org/chunsik/pq/email/service/EmailService.java
> +        Optional<EmailConfirm> existingEmailConfirmOpt = emailConfirmRepository.findByEmail(email);
오 map 이라는 함수가 있었군요!

map 과 빌더 조합해서 쓰는 것 너무 좋은거같아요 👍

2024-08-15 23:45 UTC, kimdaegeon0918 commented on src/main/java/org/chunsik/pq/email/model/EmailConfirm.java
작동은 되던데 검색해보고 돌려두든 그대로 두든 해보겠습니다

2024-08-15 23:46 UTC, kimdaegeon0918 commented on src/main/java/org/chunsik/pq/email/controller/EmailController.java
> +    @ExceptionHandler(RuntimeException.class)
그렇네요 수정해야겠습니다

2024-08-15 23:54 UTC, kimdaegeon0918 commented on src/main/java/org/chunsik/pq/email/model/EmailConfirm.java
GPT한테 물어본 결과 필드이름과 테이블의 열이름이 같으면 생략해도 되고 생략가능하면 생략하는걸 추천한다고 하네요

2024-08-17 07:44 UTC, ZZ3n approved these changes
드디어 **완**

2024-08-17 07:46 UTC, HeungY approved these changes
👍

2024-08-17 07:48 UTC, merged