feat: 로그인,회원가입,스프링 시큐리티,Jwt 기능 구현 [Jira] PQ-13(하위 이슈 PQ-22,PQ-25),PQ-34(하위 이슈 PQ-37,PQ-39)
100-hours-a-week/5-chunsik-4Q-be pull request #6
Opened 2024-08-16 07:30 UTC by HuttTheJAVA

### 개요
- 로그인,회원가입,스프링 시큐리티,Jwt 기능 구현

### 리뷰어가 꼭 봐줬으면 하는 부분
- users/login 기존의 API 명세는 메시지를 응답하지만 토큰을 응답하는 형태로 구현
- 서비스 상 회원탈퇴를 제공하지 않으므로 erd와 다르게 유저 엔티티의 탈퇴 시점 필드는 구현하지 않음.  
- 닉네임은 중복가능하게 구현(Oauth를 통해 가입하면 닉네임은 이름이며, 동명이인이 있을 수 있기 때문)
- 예외를 전역적으로 핸들링하는 RestControllerAdvice로 예외를 핸들링했는데 이 부분에 대해 피드백 해주시면 감사하겠습니다.
- Oauth의 유저 DB 저장시 비밀번호를 null 로 하려고 하였으나 DB에 null로 저장할 경우 로그인 때 DB에서 못 찾는 이슈로 인해 null -> "1234"로 변경
- 액세스, 리프래쉬 토큰 만료시 리다이렉트 요구 메시지 응답 

### Jira ISSUE Keys
- PQ-13
    - PQ-22,PQ-25
- PQ-34
    - PQ-37,PQ-39

2024-08-17 13:22 UTC, ZZ3n requested changes
- `UserDetails` 하고, `User`분리
- `refreshToken` 취급주의!

2024-08-17 13:22 UTC, ZZ3n commented on src/main/java/org/chunsik/pq/login/dto/TokenDto.java
> +    private String refreshToken;
refresh 토큰 프론트로 보낼 필요 없습니당

2024-08-17 13:22 UTC, ZZ3n commented on src/main/java/org/chunsik/pq/model/User.java
> +public class User implements UserDetails {
`UserDetails`하고 Entity `User`하고 분리해주세요

2024-08-19 04:48 UTC, HuttTheJAVA commented on src/main/java/org/chunsik/pq/login/controller/AuthController.java
> +        String refreshToken = request.get(REFRESH_TOKEN);
수정사항 반영 완료했고, PostMan으로 Access는 ResponseEntity로 응답오고, refresh는 쿠키로 응답오는 것 확인했습니다!

2024-08-19 04:48 UTC, HuttTheJAVA commented on src/main/java/org/chunsik/pq/login/controller/OauthController.java
> +        RestTemplate rt2 = new RestTemplate();
죄송합니다... 당시 심신미약 상태였습니다..

2024-08-19 04:48 UTC, HuttTheJAVA commented on src/main/java/org/chunsik/pq/login/controller/OauthController.java
> +            joinDTO.setNickname(kakaoAccount.path("profile").path("nickname").asText());
반영 완료!

2024-08-19 04:49 UTC, HuttTheJAVA commented on src/main/java/org/chunsik/pq/login/controller/OauthController.java
> +            userService.join(joinDTO, OauthProvider.KAKAO);
반영 완료!

2024-08-19 04:51 UTC, HuttTheJAVA commented on src/main/java/org/chunsik/pq/login/controller/OauthController.java
> +            e.printStackTrace();
log.error(커스텀 메시지, e.getMessage()) 형태로 변경했습니다

2024-08-19 04:51 UTC, HuttTheJAVA commented on src/main/java/org/chunsik/pq/login/controller/UserController.java
> +    @PostMapping("/test")
삭제 완료!

2024-08-19 04:51 UTC, HuttTheJAVA commented on src/main/java/org/chunsik/pq/login/dto/TokenDto.java
> +    private String refreshToken;
넵 반영했습니다

2024-08-19 04:51 UTC, HuttTheJAVA commented on src/main/java/org/chunsik/pq/model/User.java
> +public class User implements UserDetails {
반영 완료!

2024-08-19 06:07 UTC, ZZ3n approved these changes

2024-08-19 06:08 UTC, HeungY approved these changes
👍
LGTM

2024-08-19 06:09 UTC, merged